name: "Workflow name"

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment: {dev,stage,prod}'
        required: true
        default: 'dev'

jobs:
  build:
    name: "Job env: ${{ github.event.inputs.env }}"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "Hello World!"
